name: SellPortal
version: '${project.version}'
main: lv.cliquant.sellportal.Main
api-version: 1.13
authors: [ cliquant ]
softdepend: [ShopGUIPlus, HolographicDisplays, Vault, PlaceholderAPI]
description: SellPortal which sells items when drop them in portal and sends to portal owner balance!
commands:
  sellportal:
    usage: /<command>